### ISSUE TITLE
kui directory can support multi-level?

### ISSUE THREAD

**Issue by milescui** [krawaller/kranium#16]
Hi krawaller

When kui directory has many files, should how to organize them? kui directory can support multi-level?

thanks
/Miles

**Comment by krawaller** [comment]
Kranium supports multi-level directories, but you'll have to specify the whole path in the `type` like so:

``` javascript
var customComponent = K.create({
    type: 'my/custom/component'
});
```

will pick up the file from `Resources/kui/my/custom/component.js`

**Comment by milescui** [comment]
great，Very useful.

thanks
/Miles

**Comment by milescui** [comment]
Kranium will auto pick up the Kss file from Resources/kui/my/custom/component.kss?

thanks
/Miles

**Comment by krawaller** [comment]
Almost right, but from `Resources/kss/my/custom/component.kss`

**Comment by milescui** [comment]
Thanks krawaller, that solve my problem. :)

/Miles
