### ISSUE TITLE
kranium and Titanium 2.0 ? 

### ISSUE THREAD

**Issue by nvdnkpr** [krawaller/kranium#22]
Hello Jacob,
are you currently working on something toward the 2.0 release? 

Greetings
Navid

**Comment by krawaller** [comment]
Hi Navid!
I haven't really dived into the 2.0 release, so no, not yet. Is it something specific you're thinking about?

Cheers

**Comment by nvdnkpr** [comment]
No not really, I'm still glad with the 1.7/1.8 release...
does 1.8 now fully support live updates and stuff ? will it ever come ? if not, i'm still fine with the core functionality :D

**Comment by unr** [comment]
Just adding that I've been developing with Kranium successfully on both TI 1.8, and 2.0.1.GA2. No issues thus far.

**Comment by nvdnkpr** [comment]
Good to hear... with which version of kranium  ?

**Comment by unr** [comment]
The one I'm currently using in my project: KRANIUM_VERSION = "0.1.4";

**Comment by nvdnkpr** [comment]
thank you... then... i'm closing the issue
