### ISSUE TITLE
Requires node 0.4, doesn't install with 0.5 or 0.6

### ISSUE THREAD

**Issue by qdc** [krawaller/kranium#8]
I installed node 0.6.0 and 0.6.1 and failed to install kranium with sudo npm install kranium -g
Also failed with node 0.5.10
It worked with 0.4.12

To change node version  :
sudo npm install n -g
n 0.4.12

**Comment by krawaller** [comment]
Kranium 0.1.4 was just pushed to npm and should work on node 0.6. Please let me know how this works out for you!

**Comment by woss** [comment]
Hey, Krawaller still have issue with require('sys'); :)
